# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=work_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),work_win64)
  nc_cfg_config = work_win64
  nc_cmd_config = work_win64
endif
ifeq ($(config),game_win64)
  nc_cfg_config = game_win64
  nc_cmd_config = game_win64
endif

PROJECTS := nc_cfg nc_cmd

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

nc_cfg:
ifneq (,$(nc_cfg_config))
	@echo "==== Building nc_cfg ($(nc_cfg_config)) ===="
	@${MAKE} --no-print-directory -C nc_cfg -f Makefile config=$(nc_cfg_config)
endif

nc_cmd: nc_cfg
ifneq (,$(nc_cmd_config))
	@echo "==== Building nc_cmd ($(nc_cmd_config)) ===="
	@${MAKE} --no-print-directory -C nc_cmd -f Makefile config=$(nc_cmd_config)
endif

clean:
	@${MAKE} --no-print-directory -C nc_cfg -f Makefile clean
	@${MAKE} --no-print-directory -C nc_cmd -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  work_win64"
	@echo "  game_win64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   nc_cfg"
	@echo "   nc_cmd"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"