# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=work_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),work_win64)
  nc_cfg_config = work_win64
  nc_lib_config = work_win64
  nc_num_config = work_win64
  nc_mem_config = work_win64
  nc_aud_config = work_win64
  nc_iop_config = work_win64
  nc_cmd_config = work_win64
  nc_app_config = work_win64
endif
ifeq ($(config),test_win64)
  nc_cfg_config = test_win64
  nc_lib_config = test_win64
  nc_num_config = test_win64
  nc_mem_config = test_win64
  nc_aud_config = test_win64
  nc_iop_config = test_win64
  nc_cmd_config = test_win64
  nc_app_config = test_win64
endif
ifeq ($(config),play_win64)
  nc_cfg_config = play_win64
  nc_lib_config = play_win64
  nc_num_config = play_win64
  nc_mem_config = play_win64
  nc_aud_config = play_win64
  nc_iop_config = play_win64
  nc_cmd_config = play_win64
  nc_app_config = play_win64
endif

PROJECTS := nc_cfg nc_lib nc_num nc_mem nc_aud nc_iop nc_cmd nc_app

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

nc_cfg:
ifneq (,$(nc_cfg_config))
	@echo "==== Building nc_cfg ($(nc_cfg_config)) ===="
	@${MAKE} --no-print-directory -C nc_cfg -f Makefile config=$(nc_cfg_config)
endif

nc_lib: nc_cfg
ifneq (,$(nc_lib_config))
	@echo "==== Building nc_lib ($(nc_lib_config)) ===="
	@${MAKE} --no-print-directory -C nc_lib -f Makefile config=$(nc_lib_config)
endif

nc_num: nc_cfg nc_lib
ifneq (,$(nc_num_config))
	@echo "==== Building nc_num ($(nc_num_config)) ===="
	@${MAKE} --no-print-directory -C nc_num -f Makefile config=$(nc_num_config)
endif

nc_mem: nc_cfg nc_lib
ifneq (,$(nc_mem_config))
	@echo "==== Building nc_mem ($(nc_mem_config)) ===="
	@${MAKE} --no-print-directory -C nc_mem -f Makefile config=$(nc_mem_config)
endif

nc_aud: nc_cfg nc_lib nc_mem
ifneq (,$(nc_aud_config))
	@echo "==== Building nc_aud ($(nc_aud_config)) ===="
	@${MAKE} --no-print-directory -C nc_aud -f Makefile config=$(nc_aud_config)
endif

nc_iop: nc_cfg nc_lib nc_num
ifneq (,$(nc_iop_config))
	@echo "==== Building nc_iop ($(nc_iop_config)) ===="
	@${MAKE} --no-print-directory -C nc_iop -f Makefile config=$(nc_iop_config)
endif

nc_cmd: nc_cfg nc_lib nc_num nc_mem
ifneq (,$(nc_cmd_config))
	@echo "==== Building nc_cmd ($(nc_cmd_config)) ===="
	@${MAKE} --no-print-directory -C nc_cmd -f Makefile config=$(nc_cmd_config)
endif

nc_app: nc_cmd nc_aud nc_iop nc_mem nc_num nc_lib nc_cfg
ifneq (,$(nc_app_config))
	@echo "==== Building nc_app ($(nc_app_config)) ===="
	@${MAKE} --no-print-directory -C nc_app -f Makefile config=$(nc_app_config)
endif

clean:
	@${MAKE} --no-print-directory -C nc_cfg -f Makefile clean
	@${MAKE} --no-print-directory -C nc_lib -f Makefile clean
	@${MAKE} --no-print-directory -C nc_num -f Makefile clean
	@${MAKE} --no-print-directory -C nc_mem -f Makefile clean
	@${MAKE} --no-print-directory -C nc_aud -f Makefile clean
	@${MAKE} --no-print-directory -C nc_iop -f Makefile clean
	@${MAKE} --no-print-directory -C nc_cmd -f Makefile clean
	@${MAKE} --no-print-directory -C nc_app -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  work_win64"
	@echo "  test_win64"
	@echo "  play_win64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   nc_cfg"
	@echo "   nc_lib"
	@echo "   nc_num"
	@echo "   nc_mem"
	@echo "   nc_aud"
	@echo "   nc_iop"
	@echo "   nc_cmd"
	@echo "   nc_app"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"